[package]
name = "sqlx-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
